FROM node:alpine as build

WORKDIR /home/app

COPY package*.json .
RUN npm install

COPY . .

RUN npm run build

FROM nginx:latest
COPY --from=build   home/app/dist  /usr/share/nginx/html    
EXPOSE 80