name: vite-react

services:
    client:
        build:
            context: ./client
            dockerfile: Dockerfile.prod
        restart: unless-stopped
    api:
        build:
            context: ./api
            dockerfile: Dockerfile
        restart: unless-stopped
        depends_on:
            - db
    db:
        image: mongo
        volumes:
            - type: volume
              source: mydbvite
              target: /data/db
        restart: unless-stopped

    reverse-proxy:
        build:
            context: ./reverse-proxy
            dockerfile: Dockerfile.prod
        ports:
            - 80:80
        depends_on:
            - api
            - db
            - client
volumes:
    mydbvite:
        #external: true
